site_name: Hands on Introduction to High Performance Computing
site_url: https://example.com/
theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/logo.svg
  palette:
    scheme: default
    primary: indigo


markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        check_paths: true



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css


nav:
  - "Introduction": index.md
  - "EPCC": EPCC.md
  - "Why HPC?": why_HPC.md
  - "Basics of HPC systems": HPC_systems_overview.md
  - "Exercise 1 - connecting to and using a supercomputer":
    - "Overview": ex1/ex1.md
    - "Theory": ex1/theory.md 
    - "Part 1": ex1/part1.md
    - "Part 2": ex1/part2.md
    - "Part 3": ex1/part3.md
  - "Hardware and architecture details": hardware_and_architectures.md
  - "Parallel programming": parallel_programming.md
  - "Exercise 2 - running parallel programs":
    - "Overview": ex2/ex2.md
    - "Theory": ex2/theory.md
    - "Part 1": ex2/part1.md
    - "Part 2": ex2/part2.md
  - "Parallel performance": parallel_performance.md
  - "Exercise 3 - parallel performance":
    - "Overview": ex3/ex3.md
    - "Theory": ex3/theory.md
    - "Part 1": ex3/part1.md
    - "Part 2": ex3/part2.md
    - "Part 3": ex3/part3.md

  # - "Extra: Optimization": optimization.md
